version: '3.8'

services:
  tests:
    build: .
    container_name: saucedemo_tests
    volumes:
      - ./allure-results:/app/allure-results
    command: pytest tests/ --alluredir=./allure-results -v
